blank_issues_enabled: true
contact_links:
  - name: Mast. XZ Messaging
    url: https://mail.google.com/mail/?fs=1&tf=cm&source=mailto&to=mastxzmessaging@gmail.com
    about: Please contact us here.
  - name: Oxez Community
    url: https://github.com/JavascriptLearner815/laughing-oxe/discussions
    about: Please ask and answer questions and everything else that isn''t an issue here.
  - name: Mast. XZ Emergency Alarm
    url: https://github.com/JavascriptLearner815/laughing-oxe/security/policy
    about: Please report security vulnerabilities here.
